name: deploy

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  GITHUB_USER: MikyM
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install and cache PowerShell modules
      uses: potatoqualitee/psmodulecache@v5.2
      with:
        modules-to-cache: powershell-yaml

    - name: Check out Code 
      uses: actions/checkout@v3

    - name: Build
      run: |
        cd src
        dotnet restore
        dotnet build -c Release --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        cd src
        dotnet test -c Release --no-restore --no-build --verbosity minimal
  
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Pack DataExplorer
      run: |  
        cd src/DataExplorer
        dotnet pack -c Release -o out 

    - name: Push DataExplorer NuGet registry
      run: dotnet nuget push ./src/DataExplorer/out/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

    - name: Pack DataExplorer.EfCore
      run: | 
        cd src/DataExplorer.EfCore
        dotnet pack -c Release -o out 

    - name: Push DataExplorer.EfCore NuGet registry
      run: dotnet nuget push ./src/DataExplorer.EfCore/out/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

  build_docs:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - name: Restore dotnet tools
      run: dotnet tool restore
      
    - name: Docfx metadata
      run: cd ./docs && dotnet docfx metadata

    - name: Fix namespaces
      shell: pwsh
      run: cd ./docs && ./fix-nmsp.ps1 api\toc.yml

    - name: Docfx build
      run: cd ./docs && dotnet docfx build -f
      
    - name: Upload docs
      uses: actions/upload-artifact@v3
      with:
        name: docfx-site
        path: docs/_site/

  publish_docs:
    name: Publish Documentation
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout triggering branch
        uses: actions/checkout@v3
        with:
          path: base
      
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: site
      
      - name: Prepare
        run: bash base/docs/scripts/prepare.sh
      
      - name: Download documentation artifacts
        uses: actions/download-artifact@v3
        with:
          name: docfx-site
          path: site
      
      - name: Build
        run: bash base/docs/scripts/build.sh
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site