name: package-deploy

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/MikyM/index.json
        dotnet-version: 7.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Check out Code 
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution and generate base NuGet package
      run: |  
        cd /home/runner/work/DataExplorer/DataExplorer/DataExplorer
        dotnet pack -c Release -o out 
    - name: Push generated base package to NuGet registry
      run: dotnet nuget push ./DataExplorer/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Build solution and generate Ef NuGet package
      run: | 
        cd /home/runner/work/DataExplorer/DataExplorer/DataExplorer.EfCore
        dotnet pack -c Release -o out 
    - name: Push generated Ef package to NuGet registry
      run: dotnet nuget push ./DataExplorer.EfCore/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Build solution and generate Mongo NuGet package
      run: | 
        cd /home/runner/work/DataExplorer/DataExplorer/DataExplorer.MongoDb
        dotnet pack -c Release -o out 
    - name: Push generated Mongo package to NuGet registry
      run: dotnet nuget push ./DataExplorer.MongoDb/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json